gallery/urls.py
from django.urls import path
from gallery import views

app_name = 'gallery'
urlpatterns = [
    path('', views.index, name='index'),
    path('image/<int:pk>', views.image, name='image'),
    path('search/', views.search, name='search')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from gallery.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallery/', include('gallery.urls')), # include gallery urls
    path('users/', include('users.urls')), # include users urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('add/', views.add, name='add'),
    path('logout/', views.logout, name='logout'),
]

gallery/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Photography(models.Model):
    class Meta:
        verbose_name = 'Fotografia'
        verbose_name_plural = 'Fotografias'
    

    # must be a string.
    NEBULA = '1'
    STAR = '2'
    GALAXY = '3'
    PLANET = '4'

    CATEGORY_CHOICES = (
        (NEBULA, 'Nebulosa'),
        (STAR, 'Estrela'),
        (GALAXY, 'Galáxia'),
        (PLANET, 'Planeta'),
    )

    name = models.CharField(
        max_length=100,
        null=False,
        blank=False
    )
    name.verbose_name = 'Nome'

    legend = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    legend.verbose_name = 'Legenda'

    description = models.TextField(
        null=False,
        blank=False
    )
    description.verbose_name = 'Descrição'

    photo = models.ImageField(
        upload_to="fotos/%Y/%M/%d/",
        blank=True
    )
    photo.verbose_name = 'Foto'

    category = models.CharField(
        max_length=100,
        choices=CATEGORY_CHOICES,
        default=''
    )
    category.verbose_name = 'Categoria'

    is_published = models.BooleanField(default=False)
    is_published.verbose_name = 'Publicado?'

    date = models.DateTimeField(
        default=datetime.now,
        blank=False
    )
    date.verbose_name = 'Data da fotografia'

    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name='user' # Used in query 
    )
    user.verbose_name = 'Upado(a) por'

    def __str__(self) -> str:
        return f'Fotografia - @{self.name}'

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms


class LoginForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        label='Nome de login',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Ex.: Enya, Takai ...'
            }
        )
    )

    password = forms.CharField(
        max_length=70,
        label='Senha',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Digite sua senha'
            }
        )
    )


class RegisterForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        label='Nome',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Ex.: Enya, Takai ...'
            }
        )
    )

    email = forms.EmailField(
        max_length=100,
        label='Email',
        required=True,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Ex.: enya@email.com ...'
            }
        )
    )

    password_1 = forms.CharField(
        max_length=70,
        label='Senha',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Digite sua senha'
            }
        )
    )

    password_2 = forms.CharField(
        max_length=70,
        label='Confirme sua senha',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Digite sua senha novamente'
            }
        )
    )

    # validated only the name field
    def clean_name(self):
        name = self.cleaned_data.get('name')

        if name:
            name = name.strip()

            if ' ' in name:
                raise forms.ValidationError(
                    'Não é possível inserir espaços dentro do campo nome')

        return name

    def clean_password_2(self):
        pass_1 = self.cleaned_data.get('password_1')
        pass_2 = self.cleaned_data.get('password_2')

        if pass_1 != pass_2:
                raise forms.ValidationError('As senhas não são iguais')
        
        return super().clean()

gallery/views.py
from django.shortcuts import get_object_or_404, redirect, render

from gallery.models import Photography
from django.contrib import messages



# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        messages.error(request, "Você precisa se autenticar")

        return redirect('users:login')

    # we want only published photos.
    photos = Photography.objects.order_by('-date').filter(
        is_published=True
    )

    context = {
        'photos': photos
    }

    return render(request, 'gallery/index.html', context)

def image(request, pk):
    photo = get_object_or_404(Photography, pk=pk)

    context = {
        'photo': photo
    }

    return render(request, 'gallery/image.html', context)

def search(request):
    if not request.user.is_authenticated:
        messages.error(request, "Você precisa se autenticar")

        return redirect('users:login')

    photos = Photography.objects.order_by('-date').filter(
        is_published=True
    )

    q = request.GET.get('q')

    if q:
        photos = photos.filter(name__icontains=q)
        
    return render(request, 'gallery/search.html',{ 'photos': photos })

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth, messages
from django.urls import reverse

from users.forms import LoginForm, RegisterForm

# Create your views here.


def login(request):
    data = request.POST or None
    form = LoginForm(data)

    if request.method == 'POST':
        if form.is_valid():
            name = form.cleaned_data['name']
            password = form.cleaned_data['password']

            user = auth.authenticate(
                request,
                username=name,
                password=password
            )

            if user is not None:
                auth.login(request, user)

                messages.success(request, f'Login realizado com sucesso! Bem vindo, {user.get_username()}')

                return redirect(reverse('gallery:index'))
            else:
                messages.error(request, 'Não foi possível realizar o login. Verifique suas credenciais.')

                return redirect(reverse('users:login'))

    context = {
        'form': form
    }

    return render(
        request,
        'users/login.html',
        context
    )


def logout(request):
    auth.logout(request)

    messages.success(request, 'Logout realizado com sucesso')

    return redirect('users:login')


def add(request):
    ''' Accept GET and POST methods
        POST -> Register an user;
        GET -> Return the register form.
    '''
    
    data = request.POST or None

    form = RegisterForm(data)

    if request.method == 'POST':

        if form.is_valid():
            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password_1')

            if User.objects.filter(username=name).exists():
                messages.error(request, f'Já existe um usuário com o nome {name}')

                return redirect(reverse('users:add'))

            user = User.objects.create_user(
                username=name,
                email=email,
                password=password
            )

            user.save()

            messages.success(request, 'Cadastro realizado com sucesso')

            return redirect(reverse('users:login'))

    context = {
        'form': form
    }

    return render(request, 'users/add.html', context)

templates/gallery/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alura Space</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/styles/style.css' %}">    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>    
    <div class="pagina-inicial">    
        {% include 'partials/_header.html' %}
        
        <main class="principal">
            <section class="menu-lateral">
                <nav class="menu-lateral__navegacao">
                    <a href="#"><img src="{% static '/assets/ícones/1x/Home - ativo.png' %}"> Home</a>
                    <a href="{% url 'users:login' %}"><img src="{% static '/assets/ícones/1x/Mais vistas - inativo.png' %}"> Login</a>
                    <a href="{% url 'users:add' %}"><img src="{% static '/assets/ícones/1x/Novas - inativo.png' %}"> Cadastro</a>
                    <a href="{% url 'users:logout' %}"><img src="{% static '/assets/ícones/1x/Surpreenda-me - inativo.png' %}"> Logout</a>
                </nav>
            </section>
            {% block content %}
            {% endblock content %}
        </main>
        {% include 'partials/_footer.html' %}
    </div>
</body>

</html>

templates/gallery/image.html
{% extends 'gallery/base.html' %}
{% load static %}
{% block content %}
            <section class="conteudo">
                <section class="imagem">
                    <div class="imagem__conteudo">
                        <img class="imagem__imagem" src="{{photo.photo.url}}">
                        <div class="imagem__info">
                            <div class="imagem__texto">
                                <p class="imagem__titulo">{{photo.name}}</p>
                                <p class="imagem__descricao">{{photo.legend}}</p>
                                <p class="imagem__texto">{{photo.description}}</p>
                            </div>
                        </div>
                    </div>
                </section>
            </section>

{% endblock content %}

templates/gallery/index.html
{% extends 'gallery/base.html' %}
{% load static %}

{% block content %}    

               
            <section class="conteudo">
                <ul>
                    {% for message in messages %}
                        <li class="alert alert-success" role="alert">
                            {{message}}
                        </li>
                        {% endfor %}
                    </ul>   
                <section class="banner">
                    <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
                    <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
                </section>
                <section class="tags">
                    <p class="tags__titulo">Busque por tags:</p>
                    <ul class="tags__lista">
                        <li class="tags__tag">Nebulosa</li>
                        <li class="tags__tag">Estrela</li>
                        <li class="tags__tag">Galáxia</li>
                        <li class="tags__tag">Planeta</li>
                    </ul>
                </section>
                <section class="galeria">
                    <div class="cards">
                        <h2 class="cards__titulo">Navegue pela galeria</h2>
                        <ul class="cards__lista">
                            {% if not photos %}
                                <div class="imagem__texto">
                                    <p>
                                        Fotografias não encontradas
                                    </p>
                                </div>
                            {% else %}
                            {% for photo in photos %}
                                <li class="card__item">
                                    {% if not photo.photo %}
                                        <a href="{% url 'gallery:image' pk=photo.pk %}" >
                                            <img class="card__imagem" src="{% static '/assets/imagens/not-found.png' %}" alt="foto">
                                        </a>
                                    {% else %}
                                        <a href="{% url 'gallery:image' pk=photo.pk %}" >
                                            <img class="card__imagem" src="{{photo.photo.url}}" alt="foto">
                                        </a>
                                    {% endif %}
                                    <span class="card__tag">Estrelas</span>
                                    <div class="card__info">
                                        <p class="card__titulo">{{ photo.name }}</p>
                                        <div class="card__texto">
                                            <p class="card__descricao">{{ photo.legend }}</p>
                                            <span>
                                                <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                                            </span>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}   
                            {%endif%} 
                        </ul>
                    </div>
                </section>
            </section>
    
{% endblock content %}

templates/gallery/search.html
{% extends 'gallery/base.html' %}
{% load static %}

{% block content %}
    <div class="pagina-inicial">        
        <main class="principal">
            <section class="menu-lateral">
                <nav class="menu-lateral__navegacao">
                    <a href="#"><img src="{% static '/assets/ícones/1x/Home - ativo.png' %}"> Home</a>
                    <a href="#"><img src="{% static '/assets/ícones/1x/Mais vistas - inativo.png' %}"> Mais vistas</a>
                    <a href="#"><img src="{% static '/assets/ícones/1x/Novas - inativo.png' %}"> Novas</a>
                    <a href="#"><img src="{% static '/assets/ícones/1x/Surpreenda-me - inativo.png' %}"> Surpreenda-me</a>
                </nav>
            </section>
            <section class="conteudo">
                <section class="banner">
                    <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
                    <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
                </section>
                <section class="tags">
                    <p class="tags__titulo">Busque por tags:</p>
                    <ul class="tags__lista">
                        <li class="tags__tag">Nebulosa</li>
                        <li class="tags__tag">Estrela</li>
                        <li class="tags__tag">Galáxia</li>
                        <li class="tags__tag">Planeta</li>
                    </ul>
                </section>
                <section class="galeria">
                    <div class="cards">
                        <h2 class="cards__titulo">Navegue pela galeria</h2>
                        <ul class="cards__lista">
                            {% if not photos %}
                                <div class="imagem__texto">
                                    <p>
                                        Fotografias não encontradas
                                    </p>
                                </div>
                            {% else %}
                            {% for photo in photos %}
                                <li class="card">
                                    {% if not photo.photo %}
                                        <a href="{% url 'gallery:image' pk=photo.pk %}" >
                                            <img class="card__imagem" src="{% static '/assets/imagens/not_found.png' %}" alt="foto">
                                        </a>
                                    {% else %}
                                        <a href="{% url 'gallery:image' pk=photo.pk %}" >
                                            <img class="card__imagem" src="{{photo.photo.url}}" alt="foto">
                                        </a>
                                    {% endif %}
                                    <span class="card__tag">Estrelas</span>
                                    <div class="card__info">
                                        <p class="card__titulo">{{ photo.name }}</p>
                                        <div class="card__texto">
                                            <p class="card__descricao">{{ photo.legend }}</p>
                                            <span>
                                                <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                                            </span>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}   
                            {%endif%} 
                        </ul>
                    </div>
                </section>
            </section>
        </main>
    </div>
    
{% endblock content %}

templates/partials/_alerts.html
{% if messages %}
<ul>
    {% for message in messages %}
        <li class="alert alert-{{message.tags}}" role="alert">
            {{message}}
        </li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/_footer.html
{% load static %}

<footer class="rodape">
    <div class="rodape__icones">
        <a href="https://twitter.com/AluraOnline" target=”_blank” >
            <img src="{% static '/assets/ícones/1x/twitter.png' %}" alt="ícone twitter">
        </a>
        <a href="https://www.instagram.com/aluraonline/" target=”_blank” >
            <img src="{% static '/assets/ícones/1x/instagram.png' %}" alt="ícone instagram">
        </a>
    </div>
    <p class="rodape__texto">Desenvolvido por Alura</p>
</footer>

templates/partials/_header.html
{% load static %}

<header class="cabecalho">
    <a href="{% url 'gallery:index' %}">
        <img src="{% static '/assets/logo/Logo(2).png' %}" alt="Logo da Alura Space" />
    </a>

    <div class="cabecalho__busca">
        <div class="busca__fundo">
            <form action="{% url 'gallery:search' %}">
                <input class="busca__input" name="q" type="text" placeholder="O que você procura?">

                <button type="submit">
                    <img class="busca__icone" src="{% static '/assets/ícones/1x/search.png' %}" alt="ícone de search">
                </button>
            </form>
        </div>
    </div>
</header>

templates/users/add.html
{% extends 'gallery/base.html' %}
{% load static %}

{% block content %}   

<section class="galeria" style="margin-left: 5em">
    <form action="{% url 'users:add' %}" method="POST">
        {% csrf_token %}

        {% include 'partials/_alerts.html' with messages=messages %}

        <div class="row">
            {% for field in form.visible_fields %}
                <div class="col-12 col-lg-12 mb-2">
                    <label class="text-white mb-2" for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field }}

                    {% for error in field.errors %}
                        <div class="alert alert-danger mt-2">
                            {{error}}
                        </div>
                    {% endfor %}
                </div>

               
            {% endfor %}
        </div>

        <div class="col-12 text-center">
            <button class="btn btn-success col-12" style="padding: top 5px;" type="submit">Registrar</button>
        </div>
    </form>
</section>
{% endblock content %}  

templates/users/login.html
{% extends 'gallery/base.html' %}
{% load static %}

{% block content %}   

<section class="galeria" style="margin-left: 5em">
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}

        {% include 'partials/_alerts.html' with messages=messages %}

        <div class="row">
            <!-- <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                <label for="nome_login" style="color:#D9D9D9; margin-bottom: 5px;"><b>Nome de Login</b></label>
                <input type="text" class="form-control" name="nome_login" placeholder="Ex.: João Silva" required>
            </div> -->
            
            {% for field in form.visible_fields %}
                <div class="col-12 col-lg-12 mb-2">
                    <label class="text-white mb-2" for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
            {% endfor %}

            <div class="col-12 text-center">
                <button class="btn btn-success col-12" style="padding: top 5px;" type="submit">Acessar</button>
            </div>
        </div>
    </form>
</section>
{% endblock content %}   